# Generated by Django 3.0.4 on 2020-03-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200322_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movieid',
            field=models.IntegerField(default=0),
        ),
    ]
