# Generated by Django 3.0.4 on 2020-03-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20200322_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movieid',
            field=models.IntegerField(),
        ),
    ]
