# Generated by Django 3.0.4 on 2020-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200323_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movieid',
            field=models.TextField(),
        ),
    ]
